---
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ default_html }}/{{ domain }}'
    owner: '{{ root_account }}'
    group: '{{ root_account }}'
    state: directory
    mode: '0755'

- name: "Baixando wordpress"
  ansible.builtin.unarchive:
    src: 'https://wordpress.org/{{ tar_file }}'
    dest: '{{ default_html }}/{{ domain }}/'
    owner: '{{ root_account }}'
    group: '{{ root_account }}'
    mode: '0755'
    remote_src: true

- name: "Configurando o wp-config.php"
  ansible.builtin.copy:
    src: '{{ default_html }}/{{ domain }}/wordpress/wp-config-sample.php'
    dest: '{{ default_html }}/{{ domain }}/wordpress/wp-config.php'
    owner: '{{ root_account }}'
    group: '{{ root_account }}'
    mode: '0755'
    remote_src: true

- name: "Alterando algumas variaveis no arquivo wp-config.php"
  ansible.builtin.replace:
    path: '{{ default_html }}/{{ domain }}/wordpress/wp-config.php'
    regexp: '{{ item.regex }}'
    replace: '{{ item.value }}'
  loop:
    - { regex: 'database_name_here', value: '{{ database }}'}
    - { regex: 'username_here', value: '{{ bd_username }}'}
    - { regex: 'password_here', value: '{{ bd_password }}'}
    - { regex: 'localhost', value: '{{ bd_endpoint }}'}
